---
title: "Developing Data Products - Shiny Application"
author: "GAEL BERON"
date: "28/09/2017"
output: html_document
---

# Shiny Application testing the fuel consumption as the outcome of each car specificity

For a direct access to this Shiny application, <a href=''>click here</a>

This README file is the supporting documentation accompagning this Shiny application. It includes three parts:

- Instructions given for this project  
- Description of this Shiny application  
- Directives on how to visualize this Shiny application  

## 1. Instructions given for this project

This peer assessed assignment has two parts. First, you will create a Shiny application and deploy it on Rstudio's servers. Second, you will use Slidify or Rstudio Presenter to prepare a reproducible pitch presentation about your application.  

**Your Shiny Application**  

1. Write a shiny application with associated supporting documentation. The documentation should be thought of as whatever a user will need to get started using your application.  
2. Deploy the application on Rstudio's shiny server  
3. Share the application link by pasting it into the provided text box  
4. Share your server.R and ui.R code on github  

The application must include the following:  

1. Some form of input (widget: textbox, radio button, checkbox, ...)  
2. Some operation on the ui input in sever.R  
3. Some reactive output displayed as a result of server calculations  
4. You must also include enough documentation so that a novice user could use your application.  
5. The documentation should be at the Shiny website itself. Do not post to an external link.  

The Shiny application in question is entirely up to you. However, if you're having trouble coming up with ideas, you could start from the simple prediction algorithm done in class and build a new algorithm on one of the R datasets packages. Please make the package simple for the end user, so that they don't need a lot of your prerequisite knowledge to evaluate your application. You should emphasize a simple project given the short time frame.  

**Your Reproducible Pitch Presentation**  

OK, you've made your shiny app, now it's time to make your pitch. You get 5 slides (inclusive of the title slide) to pitch a your app. You're going to create a web page using Slidify or Rstudio Presenter with an html5 slide deck.  

Here's what you need  

1. 5 slides to pitch our idea done in Slidify or Rstudio Presenter  
2. Your presentation pushed to github or Rpubs  
3. A link to your github or Rpubs presentation pasted into the provided text box  

Your presentation must satisfy the following  

1. It must be done in Slidify or Rstudio Presenter  
2. It must be 5 pages  
3. It must be hosted on github or Rpubs  
4. It must contained some embedded R code that gets run when slidifying the document  

## 2. Description of this Shiny application

This Shiny application aims to visualize what the fuel consumption is depending on each of a list of car specifities as per the data set 'mtcars'. Those data are from the US magazine Motor Trend which published its in 1974. It combines 11 aspects of automobile design and performance for a collection of 32 automobiles (1973–74 models):  

- **mpg**: Miles/(US) gallon <span style="color:red;background-color:#eeeeee;padding:3px;border-radius:3px 3px 3px;border:.5px solid lightgrey">(the outcome in our study)</span>  
- **nb_cylinders** (originally 'cyl'): Number of cylinders  
- **displacement** (orig. 'disp'): Displacement (cu.in.)  
- **horsepower** (orig. 'hp'): Gross horsepower  
- **rear_axle_ratio** (orig. 'drat'): Rear axle ratio  
- **weight** (orig. 'wt'): Weight (lb/1000)  
- **quarter_mile_sec** (orig. 'qsec'): 1/4 mile time  
- **vs_engine_type** (orig. 'vs'): V/S Engine Type (0 = v-type, 1 = straight-type)  
- **transmission** (orig. 'am'): Transmission (0 = automatic, 1 = manual)  
- **nb_gears** (orig. 'gear'): Number of forward gears  
- **nb_carburator** (orig. 'carb'): Number of carburetors  

The application invites the user to select one of the variable above in order to see what the fuel consumption is (in mpg), depending of the variability of it.

The application contains 3 tabs:  

- Graphs  
- Raw Data  
- Help  
- Credits  

#### Graphs tab

This tab displays relevant informations about mpg being the outcome of the selected variable.  

- 'Slope' and 'Intercept': slope and intercept values of the linear regression `mpg ~ x` where x is the selected variable  
- 'MPG Vs X variable and linear regression': plots the mpg (y-axis) depending on the selected value (x-axis) and displays the linear regression `mpg ~ x`  
- 'Sums of Squares Graphs' contains the following sub-tabs:  
    + Total  
    + Regression  
    + Error  
    + Variance Partition  
- 'Regression coefficients' and 'Anova Table': coefficients and Anova table of the linear regression `mpg ~ x`  

#### Raw Data tab

This tab contains two boxes:  

- Raw Data  
    ---> Displays the list of the 32 cars considered in the dataset with mpg values and related x variable values.  
- Data distribution  
    ---> Displays the distribution of the data on the 2 axes.

#### Help tab

This tab includes this documentation ('README.Rmd' file)  

#### Credits tab

This tab gives details about the dataset used for this study and gives credits to the original idea of the shinny application 'SSregression' that explores Sums of Squares in linear regression.  

## 3. Directives on how to visualize this Shiny application

**Option 1 (online)**: Direct link: <a href=''>click here</a>

**Option 2 (local)**: Copy/Paste the following command into `R` console:  

<span style="background-color:#eeeeee;padding:3px;">
Install.packages("shiny")  
shiny::runGitHub("fuel_consumption_vs_cars_specificities", "gaelberon")  
</span>

**Option 3 (local)**: Download the server.R and ui.R files and place them in folder named 'fuel_consumption_vs_cars_specificities'. Open an R session and set the working directory to the folder that contains the directory 'fuel_consumption_vs_cars_specificities'. Then run the following commands:  

<span style="background-color:#eeeeee;padding:3px;">
library(shiny)  
runApp('fuel_consumption_vs_cars_specificities')  
</span>
